### ISSUE TITLE
Also manage /root/.k5login and /root/.k5users?

### ISSUE THREAD

**Issue by jcpunk** [treydock/puppet-module-root#8]
Would you be willing to add support for managing `/root/.k5login` and `/root/.k5users` to this module?

**Comment by treydock** [comment]
Looks like that would be appropriate for this module.  Would something like this work?

/root/.k5login
```
user1@EXAMPLE.COM
user2@EXAMPLE.COM
```

/root/.k5users
```
user3@EXAMPLE.COM /some/command /another/command
```

**Comment by jcpunk** [comment]
That looks fairly workable to me.  My ideal hiera would be something like:

```
root::k5login:
  - user1@EXAMPLE.COM
  - user2@EXAMPLE.COM
root::k5users:
  - user3@EXAMPLE.COM:
    - /some/command
    - /another/command
```

so that I can easily merge entries down the line.

**Comment by treydock** [comment]
#9 should do what you described, just changed the parameter names to be more descriptive of their purpose and contents.
